### ISSUE TITLE
Not recognizing .sage files correctly

### ISSUE THREAD

**Issue by robinkoestler** [n-WN/sagemath-vscode-enhanced#3]
Hey, thanks for contributing this nice tool to execute .sage files directly. However, it is not working for me. I followed the instructions of the extension, but still I am getting an error "The active file is not a SageMath file", although it is. I am using macOS 14, M1 chip and VSCode 1.87.2. Would be nice of you to fix this, thanks!

**Comment by n-WN** [comment]
It happens that I am also running macOS 14, M1 chip, it may be a problem with the VSCode version, I will check it out, thanks for the feedback

**Comment by n-WN** [comment]
> Hey, thanks for contributing this nice tool to execute .sage files directly. However, it is not working for me. I followed the instructions of the extension, but still I am getting an error "The active file is not a SageMath file", although it is. I am using macOS 14, M1 chip and VSCode 1.87.2. Would be nice of you to fix this, thanks!

Please provide a screenshot of the execution, or copy all the output of the terminal and the file name

**Comment by robinkoestler** [comment]
So, I don't know what to provide here. If I try Cmd+Shift+P and then type & run "Run SageMath file", there is a small pop-up window at the bottom reading "The active file is not a SageMath file". The Play button also does not work, it tries to use one of my Python interpreters.

Going to the terminal and typing "sage test.sage" works as expected though.

**Comment by n-WN** [comment]
> So, I don't know what to provide here. If I try Cmd+Shift+P and then type & run "Run SageMath file", there is a small pop-up window at the bottom reading "The active file is not a SageMath file". The Play button also does not work, it tries to use one of my Python interpreters.
> 
> Going to the terminal and typing "sage test.sage" works as expected though.

I understand, I'm going to study how to solve this problem now

**Comment by n-WN** [comment]
I assume you have the code runner plugin installed?

**Comment by n-WN** [comment]
> So, I don't know what to provide here. If I try Cmd+Shift+P and then type & run "Run SageMath file", there is a small pop-up window at the bottom reading "The active file is not a SageMath file". The Play button also does not work, it tries to use one of my Python interpreters.
> 
> Going to the terminal and typing "sage test.sage" works as expected though.

I assume you have the `code runner` plugin installed?

**Comment by robinkoestler** [comment]
You mean a VSCode extension? That I don't.

**Comment by n-WN** [comment]
> You mean a VSCode extension called runner? That I don't.

That problem may be a bit strange, can you cooperate with me to debug, if you can, I will send you a beta version of the plugin installation link

**Comment by robinkoestler** [comment]
Okay, lets try then!

**Comment by n-WN** [comment]
> Okay, lets try then!

You can go to the vscode plug-in market to update. I have updated it.
try

**Comment by robinkoestler** [comment]
Okay, I updated it, but it's still the same issue.

Just to double-check: If I execute my "test.sage" file from the VSCode Terminal by typing "sage test.sage", it creates a file "test.sage.py", automatically generated, and executes it. Is this common or did I link the sage command wrongly (to maybe some python executable)?

**Comment by n-WN** [comment]
> Okay, I updated it, but it's still the same issue.
> 
> 
> 
> Just to double-check: If I execute my "test.sage" file from the VSCode Terminal by typing "sage test.sage", it creates a file "test.sage.py", automatically generated, and executes it. Is this common or did I link the sage command wrongly (to maybe some python executable within sage)?

It's normal. This is the expected sage behavior, but I don't know why you can't use the plug-in normally. Can you take a screenshot?

**Comment by robinkoestler** [comment]
Actually, by accident, I just fixed it myself. Turned out, I was in the wrong language mode (in VSCode). I used "Detect language automatically", which classifies the .sage file as Python language. As I now selected the sage language, everything works as expected. Maybe you mention it in the readme or something.

 Thank you for your help still and for the extension overall.

**Comment by n-WN** [comment]
> Actually, by accident, I just fixed it myself. Turned out, I was in the wrong language mode (in VSCode). I used "Detect language automatically", which classifies the .sage file as Python language. As I now selected the sage language, everything works as expected. Maybe you mention it in the readme or something.
> 
> Thank you for your help still and for the extension overall.

By default, vscode does not have a language binding to sage, and the user-defined suffix binding will cause the plug-in to not work. Next, I will decide how to make it easier for users to use it. I will mention it in readme. In addition, I am also doing cryptography-related research. Can I leave an email to communicate with each other?

**Comment by robinkoestler** [comment]
Thank you. Yes, send me an e-mail to robin.koestler     and @uni.lu
