### ISSUE TITLE
Can this use in Windows?

### ISSUE THREAD

**Issue by LeiZhaoe** [n-WN/sagemath-vscode-enhanced#4]
Thank you for making this plugin I would like to know that this plugin can run the sagemath file directly on windows.

**Comment by n-WN** [comment]
Theory is fine, but you need to establish a link with WSL, and then I will try to be compatible with win on real machines

**Comment by LeiZhaoe** [comment]
@n-WN Zoee Thank you. I tried to run the sage file with this plugin today on ubuntu 22.04, but there seems to be no output.Request you to describe the usage in more detail, I want to use this plugin on ubuntu 22.04.
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/2c806c42-b2e9-4cef-891a-5009f544c39d)

**Comment by n-WN** [comment]
> @n-WN Zoee Thank you. I tried to run the sage file with this plugin today on ubuntu 22.04, but there seems to be no output.Request you to describe the usage in more detail, I want to use this plugin on ubuntu 22.04. ![image](https://private-user-images.githubusercontent.com/107112071/318189473-2c806c42-b2e9-4cef-891a-5009f544c39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTc4MTksIm5iZiI6MTcxMTc5NzUxOSwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MTg5NDczLTJjODA2YzQyLWIyZTktNGNlZi04OTFhLTUwMDlmNTQ0YzM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxMTE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzU5ZmRkNWU2MWQ3Yzg3MGRjODI0NzQ3ODk0ZWYyNGQ1ZmNlZWUyOWJmNGExYmZlMTI1YWU2Nzk4OGVjYzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7QrUCXbyQlNydmgon1zFFhTfc9dUChvRZHWJbHNDm4)

Simply execute sage xxx.sage in the terminal, is there an output

**Comment by n-WN** [comment]
> @n-WN Zoee Thank you. I tried to run the sage file with this plugin today on ubuntu 22.04, but there seems to be no output.Request you to describe the usage in more detail, I want to use this plugin on ubuntu 22.04. ![image](https://private-user-images.githubusercontent.com/107112071/318189473-2c806c42-b2e9-4cef-891a-5009f544c39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTc4MTksIm5iZiI6MTcxMTc5NzUxOSwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MTg5NDczLTJjODA2YzQyLWIyZTktNGNlZi04OTFhLTUwMDlmNTQ0YzM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxMTE4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzU5ZmRkNWU2MWQ3Yzg3MGRjODI0NzQ3ODk0ZWYyNGQ1ZmNlZWUyOWJmNGExYmZlMTI1YWU2Nzk4OGVjYzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G7QrUCXbyQlNydmgon1zFFhTfc9dUChvRZHWJbHNDm4)

可以的话，你可以直接说中文（

**Comment by LeiZhaoe** [comment]
@n-WN 师傅还是没有输出。
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/f813abb3-0296-4e24-91b4-74e9064f548b)

**Comment by n-WN** [comment]
> @n-WN 师傅还是没有输出。 ![image](https://private-user-images.githubusercontent.com/107112071/318189875-f813abb3-0296-4e24-91b4-74e9064f548b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTgxNjIsIm5iZiI6MTcxMTc5Nzg2MiwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MTg5ODc1LWY4MTNhYmIzLTAyOTYtNGUyNC05MWI0LTc0ZTkwNjRmNTQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxMTI0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTAwODlkNjAyNmJmYmYwYjEwOWNhZWNlMTA4MWUyMGQ1MDY5M2I5NmY5MmMzZDI5NGM2ZTg5NDIzNDE4ZTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahODIiu43hvGrCtloeFoD2FO2WGOadAXmVUKi4lSzCI)

你电脑上 SageMath 配置有问题，通过 apt 安装的吗

**Comment by LeiZhaoe** [comment]
@n-WN 是的，我在ubuntu上是直接apt安装的SageMath。

**Comment by LeiZhaoe** [comment]
@n-WN 我应该还要怎么配置才能直接使用您的插件

**Comment by n-WN** [comment]
> @n-WN 是的，我在ubuntu上是直接apt安装的SageMath。

晚点我看看，现在有点忙，不过问题不在于插件，而在于执行 `sage + 文件` 命令后，sage 无输出

**Comment by LeiZhaoe** [comment]
@n-WN 好的，非常感谢师傅。

**Comment by n-WN** [comment]
终端直接输入sage 会有内容吗

**Comment by LeiZhaoe** [comment]
@n-WN 直接输入可以显示，但是好像运行不了.sage文件
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/6bf1a522-35ed-41ea-8dc0-ebe2057fd29f)
但是把代码粘到jupter中是可以运行的:
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/b25fea48-d718-4fef-bfa6-91ae0c68dcc7)

**Comment by n-WN** [comment]
> @n-WN 直接输入可以显示，但是好像运行不了.sage文件
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/6bf1a522-35ed-41ea-8dc0-ebe2057fd29f)
> 
> 但是把代码粘到jupter中是可以运行的:
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/b25fea48-d718-4fef-bfa6-91ae0c68dcc7)
> 
> 

有点抽象，说明就是输入文件没输出，但这个和插件无关，你可以尝试重装sagemath

**Comment by n-WN** [comment]
> @n-WN 直接输入可以显示，但是好像运行不了.sage文件
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/6bf1a522-35ed-41ea-8dc0-ebe2057fd29f)
> 
> 但是把代码粘到jupter中是可以运行的:
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/b25fea48-d718-4fef-bfa6-91ae0c68dcc7)
> 
> 

以文件模式运行时需要退出当前交互式sage

**Comment by LeiZhaoe** [comment]
@n-WN 我退出交互模式然后在运行也是没输出，我今天才装的Sagemath。
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/ef55b869-7542-480a-968b-f92416251679)

**Comment by n-WN** [comment]
> @n-WN 我退出交互模式然后在运行也是没输出，我今天才装的Sagemath。
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/ef55b869-7542-480a-968b-f92416251679)
> 
> 

所以说比较奇怪，但正常来说不应该这样

**Comment by LeiZhaoe** [comment]
@n-WN 确实，我就是看到这个插件可以在vs直接运行sage文件就想着试一下，其实之前我都是在Win下的jupter下运行的sage。

**Comment by n-WN** [comment]
> @n-WN 确实，我就是看到这个插件可以在vs直接运行sage文件就想着试一下，其实之前我都是在Win下的jupter下运行的sage。

过两周我想办法兼容下win

**Comment by LeiZhaoe** [comment]
@n-WN 嗯嗯，如果能够兼容的话那简直是太棒了。提前谢谢师傅。

**Comment by n-WN** [comment]
> @n-WN 我退出交互模式然后在运行也是没输出，我今天才装的Sagemath。 ![image](https://private-user-images.githubusercontent.com/107112071/318204484-ef55b869-7542-480a-968b-f92416251679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzExMjEsIm5iZiI6MTcxMTg3MDgyMSwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MjA0NDg0LWVmNTViODY5LTc1NDItNDgwYS05NjhiLWY5MjQxNjI1MTY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQwNzQwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2MwMjNiYWUyYzhmZDRlMjc3ZjFkOTY0MzRiODM5YjdhZjUwN2Y3MmM0YmY2MzJhNTExMDk4NWI5NTFhMmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a3UkX8UgVcIbNZtwJsFVJfgv-nHHnLsreS2H6OaqaLk)

https://doc.sagemath.org/html/en/installation/linux.html#sec-gnu-linux

**Comment by LeiZhaoe** [comment]
@n-WN 使用这个命令就可以直接安装sagemath10了嘛，我刚刚试了下好像我的还是9.5.
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/e3a50d0b-75f3-446b-aae4-27f91a7159dd)

**Comment by n-WN** [comment]
> @n-WN 使用这个命令就可以直接安装sagemath10了嘛，我刚刚试了下好像我的还是9.5. ![image](https://private-user-images.githubusercontent.com/107112071/318257571-e3a50d0b-75f3-446b-aae4-27f91a7159dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODIyODksIm5iZiI6MTcxMTg4MTk4OSwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MjU3NTcxLWUzYTUwZDBiLTc1ZjMtNDQ2Yi1hYWU0LTI3ZjkxYTcxNTlkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMDQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzY3NjI0MWRjNTY2MjViNDhiNzMxYWE1OGZjMmJmZDkyMjBkZTdmYmQ5ZjEyYWUwZWE2N2I2ZDk0M2UyMDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WtGRbqRyRh2PMfwIYFj2ys8AWW7QEhdpgnPhSkd3Z1I)

是的 不过你去build目录下直接启动.sage文件试试呢

**Comment by LeiZhaoe** [comment]
@n-WN 我在执行到最后一步时出现了这个:
![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/be632e83-14cf-4960-b1a0-df3fe2946fa5)

**Comment by n-WN** [comment]
> @n-WN 我在执行到最后一步时出现了这个:
> 
> ![image](https://github.com/n-WN/sagemath-vscode-enhanced/assets/107112071/be632e83-14cf-4960-b1a0-df3fe2946fa5)
> 
> 

奇怪的乱碼（试试这个？

https://hello-ctf.com/HC_envSet/Crypto/#sagemath

**Comment by seojihyuk26** [comment]
It's not working. I'm using wsl and your command

> **wsl** cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
> /bin/bash: line 1: cd: c:Usersseojicodesage: No such file or directory

Even though it should be 

>  cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
This command work fine for me.
You have to remove **wsl** before cd

**Comment by n-WN** [comment]
Thank you very much, it will be fixed soon

> It's not working. I'm using wsl and your command
> 
> > **wsl** cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
> > /bin/bash: line 1: cd: c:Usersseojicodesage: No such file or directory
> 
> Even though it should be
> 
> > cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
> 
> This command work fine for me. You have to remove **wsl** before cd

**Comment by n-WN** [comment]
> It's not working. I'm using wsl and your command
> 
> > **wsl** cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
> > /bin/bash: line 1: cd: c:Usersseojicodesage: No such file or directory
> 
> Even though it should be
> 
> > cd "c:\Users\seoji\code\sage" && wsl sage "test.sage"
> 
> This command work fine for me. You have to remove **wsl** before cd

fixed

**Comment by n-WN** [comment]
> Thank you for making this plugin I would like to know that this plugin can run the sagemath file directly on windows.

可以协助我测试下吗，我目前没有win系统，无法测试wsl

**Comment by LyferLu** [comment]
> @n-WN Zoee Thank you. I tried to run the sage file with this plugin today on ubuntu 22.04, but there seems to be no output.Request you to describe the usage in more detail, I want to use this plugin on ubuntu 22.04. ![image](https://private-user-images.githubusercontent.com/107112071/318189473-2c806c42-b2e9-4cef-891a-5009f544c39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTAxOTIsIm5iZiI6MTcxNTY0OTg5MiwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MTg5NDczLTJjODA2YzQyLWIyZTktNGNlZi04OTFhLTUwMDlmNTQ0YzM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMTI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTJlZGI1YTA4OWY1NWUwZGRiMmFkNTBkODI4NWEwZDRlNGYyZDBkZjMxOWZhMGZkY2MwMTliMTU4NWE2ZWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cLRlE4k6pYGLM62j7NTW0lBxJyTgdEg-m9KEIGOiRZ0)

看起来似乎是因为没有import导致的

**Comment by n-WN** [comment]
> > @n-WN Zoee Thank you. I tried to run the sage file with this plugin today on ubuntu 22.04, but there seems to be no output.Request you to describe the usage in more detail, I want to use this plugin on ubuntu 22.04. ![image](https://private-user-images.githubusercontent.com/107112071/318189473-2c806c42-b2e9-4cef-891a-5009f544c39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTAxOTIsIm5iZiI6MTcxNTY0OTg5MiwicGF0aCI6Ii8xMDcxMTIwNzEvMzE4MTg5NDczLTJjODA2YzQyLWIyZTktNGNlZi04OTFhLTUwMDlmNTQ0YzM5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMTI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTJlZGI1YTA4OWY1NWUwZGRiMmFkNTBkODI4NWEwZDRlNGYyZDBkZjMxOWZhMGZkY2MwMTliMTU4NWE2ZWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cLRlE4k6pYGLM62j7NTW0lBxJyTgdEg-m9KEIGOiRZ0)
> 
> 
> 
> 看起来似乎是因为没有引入import导致的

不太像，这里是没有import sage的话会报错，而不是没有任何输出

**Comment by LyferLu** [comment]
![截图 2024-05-15 14-04-32](https://github.com/n-WN/sagemath-vscode-enhanced/assets/68511783/b3b213ee-1640-470d-9b99-c23e3e44969a)
![截图 2024-05-15 14-04-39](https://github.com/n-WN/sagemath-vscode-enhanced/assets/68511783/0d7c9461-0023-4c22-963b-e6814aba5fc2)
在win中不管是提前连接wsl运行脚本，还是运行脚本后连接wsl，皆未复现此问题。请提供更多信息。

**Comment by n-WN** [comment]
> ![截图 2024-05-15 14-04-32](https://private-user-images.githubusercontent.com/68511783/330678517-b3b213ee-1640-470d-9b99-c23e3e44969a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTQxMTMsIm5iZiI6MTcxNTc1MzgxMywicGF0aCI6Ii82ODUxMTc4My8zMzA2Nzg1MTctYjNiMjEzZWUtMTY0MC00NzBkLTliOTktYzIzZTNlNDQ5NjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMDU1NDk0NjEwYzExMmU2MjcwYjg0N2I1OWI1YTA3ZmExMGZiMTY1ZDQ0NDM4NjZhYTI3MTViNTQ3YjE2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ufxco8VUwnaucNWay3lzI5ASJ1SXMRWS7agXh48XAgw) ![截图 2024-05-15 14-04-39](https://private-user-images.githubusercontent.com/68511783/330678561-0d7c9461-0023-4c22-963b-e6814aba5fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTQxMTMsIm5iZiI6MTcxNTc1MzgxMywicGF0aCI6Ii82ODUxMTc4My8zMzA2Nzg1NjEtMGQ3Yzk0NjEtMDAyMy00YzIyLTk2M2ItZTY4MTRhYmE1ZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZWU4OThjZmRhODgzNzVjOTM2YThmOWM0ZjU5MmU4OWNhM2JiYzYxNjRlYTk3NzBhNjI0ZTMzMzZhNjkxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.En8ZiqD2wXFyPy8M8EYwEJGl0DfZ2qJ_LwguJiiAYmY) 在win中不管是提前连接wsl运行脚本，还是运行脚本后连接wsl，皆未复现此问题。请提供更多信息。

哈哈，一部分原因是我已经在前段时间发布新版本了；不过这条issue的最初的问题应该是用户sage安装有问题导致，与当时的插件无关

**Comment by n-WN** [comment]
> @n-WN 嗯嗯，如果能够兼容的话那简直是太棒了。提前谢谢师傅。

已经兼容 Windows，并且同时支持直接调用 wsl 默认机器
